### ISSUE TITLE
Should functions referring to Matrix be renamed?

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-algorithm#110]
I had created some functions in `mir.ndslice.traits` and `mir.ndslice.slice` that make specific reference to Matrix, such as `isMatrix`, `isUniversalMatrix`, or `CanonicalMatrix`. 

There was a discussion recently on the forum about operators and whether * should be dot product/matrix multiplication or element-wise multiplication. In some other linear algebra libraries, like Eigen, they have an Array class and a Matrix class, where those operators are defined differently. Using Matrix in this way precludes any future development along those lines. 

This would mean changing the above functions to something like `isSlice2d`, `isUniversalSlice2d`, or `CanonicalSlice2d`. This would require deprecating the current functions and replacing them with new ones. I would probably also make similar changes to the `Vector` or `Tensor` functions, to keep them consistent. 

So I suppose I'm wondering if it makes sense for me to do this, or if I'm just being paranoid?

**Comment by 9il** [comment]
We can do it when a good matrix structure be included into mir.

**Comment by jmh530** [comment]
Fair enough. I will close for now.
