### ISSUE TITLE
Sometimes UT docs above function signatures

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-algorithm#112]
In the [documentation for map](http://docs.algorithm.dlang.io/latest/mir_ndslice_topology.html#.map), there is some initial documentation, associated with the template, and then some unittests, and then a final function signature at the bottom. I think it would be easier to read if the unittests are at the end. 

I'm not sure if this is a broader issue with ddoc (perhaps because it does the template and the unittests before the functions) or with the custom ddoc that mir-algorithm uses.

**Comment by 9il** [comment]
It is DDOC issue

**Comment by jmh530** [comment]
Okay, I will close here and submit on bugzilla.

**Comment by jmh530** [comment]
https://issues.dlang.org/show_bug.cgi?id=18022
