### ISSUE TITLE
prod only works on 1-dimensional slices

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-algorithm#115]
prod in mir.math.numeric is defined for ranges. There is no issue calling it on 1-dimensional slices. However, calling it on 2-dimenisonal (or more) slices results in an error because fronting them does not produce the appropriate type for the template constraint to work.

```
unittest
{
    import mir.ndslice.topology : iota;
    import mir.math.numeric : prod;

    auto x = iota([2, 3]);
    auto y = x.prod; //generates error
}
```

**Comment by 9il** [comment]
Just ndwrapper is required

**Comment by 9il** [comment]
Fixed in master
