### ISSUE TITLE
Convert 1d slice of 1d slices to packed slice

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-algorithm#116]
I need to convert a 1d slice of 1d slices with packsOf = [1] to a packed slice with packsOf = [1, 1]. It isn't obvious to me how to accomplish this simply. 

The code below shows a simple use case: using byDim and then map. I have tried a few different options and left in a failed attempt with unpack.

A consequence of this is that I have some real trouble converting the result of byDim and map back into the original shape (when using byDim!1 instead of byDim!0). Ideally, I would just unpack it and then transpose it, effectively reversing the commands of byDim. However, this does not work with packsOf = [1].

Also, I think resolving Issue #58 as I recall running into this difficulty there as well.

```
unittest
{
    import mir.ndslice.topology : iota, byDim, map, unpack;
    import mir.ndslice.slice : packsOf;
    
    auto x = iota([2, 5]);
    auto y = x.byDim!0;
    assert(packsOf!(typeof(y)) == [1, 1]);
    auto z = y.map!(a => a + 1); //also happens with auto z = y.map!(a => a.map!(a => a + 1));
    assert(packsOf!(typeof(z)) == [1]);
    auto zz = z.unpack;
    assert(packsOf!(typeof(zz)) == [1, 1]); //error, this does not work
}
```

**Comment by 9il** [comment]
unpack can not know about structure of the internal dimensions.

Sure, this functionality should be added. It should work the same way as ndslice[]=ndarray assigns and http://docs.algorithm.dlang.io/latest/mir_ndslice_allocation.html#shape . Plus a special allocation function

**Comment by 9il** [comment]
Can be used with http://docs.algorithm.dlang.io/latest/mir_ndslice_fuse.html (requires reallocation) and `pack`

**Comment by jmh530** [comment]
Great.
