### ISSUE TITLE
FYI: DMD performance regression heavily affects mir-algorithm build time

### ISSUE THREAD

**Issue by n8sh** [libmir/mir-algorithm#120]
On my machine I noticed that running unittest-release with DMD took strangely long. It seems like this is a performance regression in DMD.

[Most recent build times](
https://travis-ci.org/libmir/mir-algorithm/builds/325109138), DMD is dramatically slower than LDC:

| build        |    time       |
|--------------|---------------|
| DMD linux64  | 11 min 54 sec |
| DMD mac64    |  16 min 55 sec |
| LDC linux64  |  4 min 14 sec |
| LDC mac64    |  3 min 54 sec |

[Looking back 3 days before that](https://travis-ci.org/libmir/mir-algorithm/builds/324052159), DMD times were close to LDC times but DMD-beta was very slow:

| build            |    time                       |
|------------------|-------------------------------|
| DMD linux64      |  3 min 16 sec                 |
| DMD mac64        |  5 min  4 sec                 |
| LDC linux64      |  2 min  7 sec                 |
| LDC mac64        |  2 min 59 sec                 |
| DMD-beta linux64 |  9 min 32 sec                 |
| DMD-beta mac64   | 10 min 56 sec (then aborted!) |

**Comment by n8sh** [comment]
Typo: most recent mac64 DMD time was **16 minutes**, not 6 minutes.

**Comment by n8sh** [comment]
The weird slowness [appears to be related to inlining.](https://forum.dlang.org/post/gevcbtueeiscqipqmmip@forum.dlang.org)
>On my mac laptop running DMD 2.078.0, building and running the mir-algorithm unittests takes 8 seconds normally but takes ~3 minutes 49 seconds with dub options "releaseMode", "optimize", "inline", "noBoundsCheck".

>When I remove the "inline" option the build + test time becomes <10 seconds.

**Comment by n8sh** [comment]
[According to the wiki](https://wiki.dlang.org/DMD_Source_Guide#Inliner) inlining is part of DMD's "frontend". If that's the case then this problem will appear in the next release of LDC because (also [according to the wiki](https://wiki.dlang.org/LDC)) LDC "uses the official DMD frontend".

**Comment by thewilsonator** [comment]
LDC does, but we disable their inlining and use LLVMs instead,

**Comment by 9il** [comment]
Should be filled into DMD (probably already?)
