### ISSUE TITLE
Runnable example for mapSubSlices/pairwiseMapSubSlices fails

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-algorithm#134]
When I run the documentation examples on the website, I get the below for mapSubSlices and a similar one for the pairwise version. 
```
onlineapp.d(12,10): Error: no property 'sliced' for type 'int[2][]'
dmd failed with exit code 1.
```

I would think this would not be an issue as `mir.ndslice.topology` imports `import mir.ndslice.slice;` Maybe those top-line imports are not included in the runnable examples?

**Comment by wilzbach** [comment]
> Maybe those top-line imports are not included in the runnable examples?

Well, the example script just adds an import to the current module (like you would do yourself).

**Comment by wilzbach** [comment]
For Phobos we went with the approach of using a [separate tool](https://github.com/dlang/tools/blob/master/tests_extractor.d) to check that all imports are correctly set and that no private functions are used.
Other ones:
- always include `mir.ndslice`
- use `public import`

**Comment by jmh530** [comment]
I mean it’s not picking up the mir.ndslice.slice import at the top of
mir.ndslice.topology.

**Comment by wilzbach** [comment]
That's expected. It just runs the code 1:1 as it is in the example block.

**Comment by jmh530** [comment]
@wilzbach Shouldn't we also use the tool here?

**Comment by 9il** [comment]
All examples pass now
