### ISSUE TITLE
over-splitting repos + repo names confusing

### ISSUE THREAD

**Issue by timotheecour** [libmir/mir-algorithm#137]
/cc @9il 
current naming is confusing:
```
mir-algorithm
Core algorithm library and a home for Dlang multidimensional array package - ndslice

mir
Mir Algorithm, Mir Random, Sparse tensors, Hoffman
```

wouldn't these work better?
s/mir-algorithm/mir-core/ (or mir-slice?)

also, is there a need to split into so many different repos? seems to be causing frequent issues, eg https://github.com/libmir/dcv/issues/126

**Comment by wilzbach** [comment]
> also, is there a need to split into so many different repos? 

If library size is a concern, sub packages like e.g. vibe.d uses them could be an easy alternative.

**Comment by wilzbach** [comment]
> sub packages like e.g. vibe.d uses them

Example for those not so familiar with Vibe.d

```json
"dependencies" : {
    "vibe-d:core" : "~>0.8.0-beta.6",
}
```

https://github.com/thaven/oauth/blob/master/dub.json

**Comment by nervecenter** [comment]
I agree. If Mir is to compete with, for example, NumPy, it needs to be just as easy to use. Using NumPy is as easy as

`pip3 install numpy
python3
>>import numpy as np
>>import numpy.linalg`

There should be one meta import for dub.json, maybe some sub packages as wilzbach suggested:

`"dependencies" : {
    "mir" : "~>xxxxx",
}`

There should be at most two imports for any given use case.

`import mir, mir.linalg;`

If GPU integration is ever had, it should be as simple as appending the GPU versions of each module:

`import mir.gpu, mir.linalg.gpu;`

Current naming and splitting between mir, mir.algorithm, mir.ndslice, lubeck, etc. is ridiculously confusing. Take it back to the drawing board.

**Comment by jmh530** [comment]
On a somewhat related point on names, am I wrong to think it's weird that they are named slices, but opSlice is no longer defined?

```
import std.stdio : writeln;
import mir.ndslice.allocation : slice;
import mir.ndslice.topology : iota;

void main()
{
    auto x = iota(6).slice;

    writeln(x);
    writeln(x[2:3]); // error
}
```

**Comment by wilzbach** [comment]
Why x[2:3] - opSlice would be x[2..3]

**Comment by 9il** [comment]
`mir` repo would be reworked for in the long term future. In the same time I can not agree about overslitting. Splitting helps to do not repeat Phobos bad decisions
