### ISSUE TITLE
Broadcasting implementation

### ISSUE THREAD

**Issue by ShigekiKarita** [libmir/mir-algorithm#140]
I have implemented [broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html) function for ndslice in my ndslice based library [grain](https://github.com/ShigekiKarita/grain/blob/6c1a930d2c7c38fd3890158a96ba0faae046b65d/source/grain/functions/common.d#L251). 

``` d
@nogc nothrow pure @safe
unittest {
    import mir.ndslice;
    auto a = iota(3, 1);
    auto b = iota(1, 2);
    auto x = broadcast(a, b);
    assert(x[0] == [[0, 0], [1, 1], [2, 2]]);
    assert(x[1] == [[0, 1], [0, 1], [0, 1]]);
    assert(x[0].slice + x[1].slice == [[[0, 1], [1, 2], [2, 3]]]);
}
```

I want to port this function to mir-algorithm instead of numir because it is very useful (e.g., matmul, byDim combination or any batch processing) and it is already `@nogc nothrow pure @safe`.

If you approve this function, I have two questions.
- which module to add this function?
- is already there any function similar to `numir.core.utility.Ndim` in mir-algorithm that returns the number of dimensions?

Thanks

**Comment by 9il** [comment]
Looks good and can be added. version `D_BetterC` that can be used to support code with and without exceptions. I think function can throw if no `D_BetterC` is set (should be reflected in the docs).

> which module to add this function?

ndslice.topology

> is already there any function similar to numir.core.utility.Ndim in mir-algorithm that returns the number of dimensions?
Yes,
http://docs.algorithm.dlang.io/latest/mir_ndslice_slice.html#.packsOf
```
packsOf!(S)[0];
```

But please add `Ndim` to ndslice.slice, its API is more convenient.

**Comment by 9il** [comment]
btw, op= operators already have some kind of broadcasting
http://docs.algorithm.dlang.io/latest/mir_ndslice_slice.html#.Slice.opIndexOpAssign.2

**Comment by 9il** [comment]
Let's close it because it doesn't cover what @jmh530 wants. If one has a use case where this would be applicable feel free to reopen.
