### ISSUE TITLE
Runnable examples don't compile.

### ISSUE THREAD

**Issue by veelo** [libmir/mir-algorithm#141]
Several runnable examples give compile errors.
http://docs.algorithm.dlang.io/latest/mir_ndslice_topology.html#.iota first example:
```
onlineapp.d(15,5): Error: static assert:  `is(DeepElementType!(typeof(slice)) == sizediff_t)` is false
dmd failed with exit code 1.
```

http://docs.algorithm.dlang.io/latest/mir_ndslice_topology.html#.reshape last exaple:
```
onlineapp.d(26,9): Error: undefined identifier `iota` in module `onlineapp`
dmd failed with exit code 1.
```

http://docs.algorithm.dlang.io/latest/mir_ndslice_topology.html#.indexed:
```
onlineapp.d(10,30): Error: template `mir.ndslice.topology.indexed` cannot deduce function from argument types `!()(int[], int[])`, candidates are:
.dub/packages/mir-algorithm-1.0.2/mir-algorithm/source/mir/ndslice/topology.d(2945,5):        `mir.ndslice.topology.indexed(Field, SliceKind kind, ulong[] packs, Iterator)(Field source, Slice!(kind, packs, Iterator) indexes)`
onlineapp.d(13,47): Error: template `mir.ndslice.topology.retro` cannot deduce function from argument types `!()(int[])`, candidates are:
.dub/packages/mir-algorithm-1.0.2/mir-algorithm/source/mir/ndslice/topology.d(2057,6):        `mir.ndslice.topology.retro(SliceKind kind, ulong[] packs, Iterator)(Slice!(kind, packs, Iterator) slice) if (packs.length == 1)`
dmd failed with exit code 1.
```

and probably others.

**Comment by jmh530** [comment]
@veelo This is usually because the functions were imported at a global scope or something and have not been imported at the unittest scope. All it usually takes is adding additional imports for whatever is missing. It would be nice if the ability to test for this was in the CI or something.

**Comment by wilzbach** [comment]
Here's the script we use for phobos:

https://github.com/dlang/tools/blob/master/tests_extractor.d

And then we run all resulting files (though compiling them should be enough).

**Comment by 9il** [comment]
@wilzbach Thanks, would be it possible to add it to dmd fe / dub?

**Comment by wilzbach** [comment]
> would be it possible to add it to dmd fe / dub?

An attempt: https://github.com/dlang/tools/pull/351
Alternatively, sth. like the following should work:

```sh
wget https://raw.githubusercontent.com/dlang/tools/6b7ef76d679563e6fccef2a6b437008d96459e95/tests_extractor.d
dub ./tests_extractor.d -i source
find out | xargs -I{} dmd -unittest -Isource -c {}
```

**Comment by wilzbach** [comment]
A quick start: https://github.com/libmir/mir-algorithm/pull/142

**Comment by 9il** [comment]
Thanks @wilzbach
