### ISSUE TITLE
DMD crashes building mir-algorithm

### ISSUE THREAD

**Issue by thewilsonator** [libmir/mir-algorithm#158]
see e.g. https://github.com/dlang/dmd/pull/8940

the release of 3.0.0 seems to generate a  (in)equality comparison between a `const(long[1])` and `long[0]` that causes the backend to crash in optimising it to a memcmp.

**Comment by thewilsonator** [comment]
offending line  is https://github.com/libmir/mir-algorithm/blob/master/source/mir/ndslice/topology.d#L322
```d
auto slice = iota(2, 3).universal.assumeContiguous;
...
assert(slice._strides == []); // <<<<
```

**Comment by thewilsonator** [comment]
If you could dust mite that to a minimal test case that would be wonderful, I'm about to go to sleep, I'll start on fixing it tomorrow.

**Comment by 9il** [comment]
This is two DMD bugs. The first cause a wrong result for `slice._strides`. It should be zero length static array. The second is compression of non-zero static array with [] that is fails to compile. I am closing this since it is not mir bug.
