### ISSUE TITLE
Failed to run a documentation example

### ISSUE THREAD

**Issue by kdmult** [libmir/mir-algorithm#211]
Running any example causes the following output.
---
Unresolvable dependencies to package mir-algorithm:
  onlineapp ~master depends on mir-algorithm ~>3.5.5
---

**Comment by 9il** [comment]
it is an issue of the `run.dlang.io` it doesn't update the packages well

**Comment by PetarKirov** [comment]
I fixed the issues related to https://run.dlang.org and https://tour.dlang.io and the latest deployment should now have 3.6.3, and so the documentation examples should now work.

**Comment by 9il** [comment]
Thank uou
