### ISSUE TITLE
mir.math.sum documentation examples do not work

### ISSUE THREAD

**Issue by tastyminerals** [libmir/mir-algorithm#226]
[Examples](http://docs.algorithm.dlang.io/latest/mir_math_sum.html) for **mir.math.sum** stopped working.

First, pressing "run" returns.
```
Application output (1: )
Compilation output: 
Unresolvable dependencies to package mir-algorithm:
  onlineapp ~master depends on mir-algorithm ~>3.3.9

Unresolvable dependencies to package mir-algorithm:
  onlineapp ~master depends on mir-algorithm ~>3.3.9
```
* The above does not exclusively apply to **mir.math.sum** but to a bunch of **mir.algorithm** doc pages in general.

Second, recreating the example code in [run.dlang.io](https://run.dlang.io) 
```d
void main() {
    import mir.ndslice.slice: sliced;
    import mir.ndslice.topology: map;
    auto ar = [1, 1e100, 1, -1e100].sliced.map!"a * 10_000";
    const r = 20_000;
    assert(r == ar.sum!"kbn");
    assert(r == ar.sum!"kb2");
    assert(r == ar.sum!"precise");
}
```
throws the following exception below.
```
onlineapp.d(34,15): Error: no property `sum` for type `mir.ndslice.slice.Slice!(MapIterator!(double*, naryFun), 1LU, cast(mir_slice_kind)2)`
onlineapp.d(35,15): Error: no property `sum` for type `mir.ndslice.slice.Slice!(MapIterator!(double*, naryFun), 1LU, cast(mir_slice_kind)2)`
onlineapp.d(36,15): Error: no property `sum` for type `mir.ndslice.slice.Slice!(MapIterator!(double*, naryFun), 1LU, cast(mir_slice_kind)2)`
dmd failed with exit code 1.
```

**Comment by 9il** [comment]
The up to date docs: http://mir-algorithm.libmir.org/mir_math_sum.html

**Comment by tastyminerals** [comment]
Yes, the up to date docs are up to date but the example code for `sum` algorithms does not work. Please run it on [run.dlang.io](run.dlang.io) and verify:
```d
/+dub.sdl:
dependency "mir" version="~>3.2.0"
dependency "mir-algorithm" version="~>3.7.17"
+/
import mir.ndslice.slice: sliced;
import mir.ndslice.topology: map;

void main()
{
    auto arr = [1, 2, 3.9, 3.1, -1.4, 23].sliced;
	auto ar = [1, 1e100, 1, -1e100].sliced.map!"a * 10_000";
	const r = 20_000;
	assert(r == ar.sum!"kbn");
	assert(r == ar.sum!"kb2");
	assert(r == ar.sum!"precise");
}
```

**Comment by tastyminerals** [comment]
Should I use `std.algorithm.sum` instead?

**Comment by tastyminerals** [comment]
Why I bump this is because of the following. 

Maybe Google fine-tuned the results for me but when I want to look up some Mir library docs and google for "mir ndslice docs" or something similar, I constantly get first results to old version of Mir library docs: http://docs.algorithm.dlang.io/latest/mir_ndslice.html

While the new version is this one: http://mir-algorithm.libmir.org/mir_ndslice.html

This is bad because some if not many examples in the older version simply do not work. Also I noticed discrepancy in documentation and missing examples in the older version. I am not sure how this can be fixed.

**Comment by jmh530** [comment]
@tastyminerals You should open a new issue recommending forwarding the the docs.algorithm.dlang.io docs to the new ones, or something to that effect. 

I also sometimes get annoyed with google recommending the wrong page.
