### ISSUE TITLE
Add Array Broadcasting

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-algorithm#233]
I have been playing with some code that potentially allows for a mixing of 1-dimensional and 2-dimensional slices in calculations and have found it quite difficult. One of the particular hangups is adding a 1-dimensional slice to a 2-dimensional slice whose shape is vector-like (as in NX1 shape). opBinary is not defined in this case because zip only works for slices with the same number of dimensions. 

One potential solution is either to add an opBinary specialization for this case (or perhaps a separate add function) with similar behavior as in R or [Numpy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.add.html) In R, if you add a vector to a matrix that is either NX1 or 1XN, then it returns a comforming matrix with each of the elements added. Adding other matrix shapes results in broadcasting whereby the vector is coerced to a matrix shape by repeating it a sufficient number of times. Numpy takes a more consistent approach to array broadcasting, but just having the vector/matrix addition work as in R for 1XN matrices. Otherwise it uses broadcasting.

**Comment by 9il** [comment]
Python has eager binary operators, while Mir's are lazy.
```
    auto opBinary(string op, RIterator, size_t RN, SliceKind rkind)
        (scope return Slice!(RIterator, RN, rkind) rhs) scope return
        if(N == RN && (kind == Contiguous && rkind == Contiguous || N == 1) && op != "~")
    {
        import mir.ndslice.topology: zip, map;
        return zip(this, rhs).map!("a " ~ op ~ " b");
    }
```

To make a fast lazy `zip.map` both arguments must be contiguous or 1-dimensional. Otherwise, we would need to use memory allocation or a slow version of `zip` that constructs an iterator that requires divide operation for each data access. Both alternatives are slow.

**Comment by jmh530** [comment]
I'm sympathetic to zip and opBinary being fast and lazy and not changing them. I had also suggested adding a separate function (e.g. zipBroadcast), mainly for ease of use. 

Also, below works without error and is closest to my use case. It could probably be generalized further, though it wouldn't handle the broadcast case. 

/+dub.sdl:
dependency "mir-algorithm" version="~>3.7.28"
+/

import mir.ndslice;
import std.stdio : writeln;

void main() {
    auto A = [0.05, 0.15].sliced(2);
    auto B = [0.1, 0.45].sliced(2, 1);
    auto C = A + B.byDim!1[0];
    writeln(C);
}

**Comment by 9il** [comment]
added `squeeze` and `unsqueeze` in`v3.7.29`

**Comment by 9il** [comment]
We can construct a `zipBroadcast`, however, this wouldn't be a `Slice` while `zip` produces the `Slice` type over `ZipIterator`.

Why not use an eager computation in this case like the following example?
```d
aMatrix[] += someVector;
//or
aMatrix.transposed[] += someVector;
```

This works well and fast, doesn't require allocations.

**Comment by jmh530** [comment]
@9il Only downside is that I never remember to use the []...

**Comment by ShigekiKarita** [comment]
FYI I previously wrote numpy-like broadcasting using `repeat` for the same dim slices. https://github.com/ShigekiKarita/mir-algorithm/commit/b60c90e6cc127d87e1d0069d9fa2033f45af201e

**Comment by jmh530** [comment]
@ShigekiKarita Thanks. Forgot about that!

**Comment by jmh530** [comment]
@ShigekiKarita Is there any reason why the broadcast PR [here](https://github.com/libmir/mir-algorithm/issues/140) was closed? It looks like you have made some improvements to it in `grain`. It looks like some `unsqueeze` functionality is not currently supported, but `unsqueeze` got moved over from `numir`.

**Comment by 9il** [comment]
I am not sure, but maybe I had closed it because the lazy binary operation had been added.

**Comment by ShigekiKarita** [comment]
Me neither. If you need, I will send PR again with https://github.com/ShigekiKarita/mir-algorithm/commit/b60c90e6cc127d87e1d0069d9fa2033f45af201e

**Comment by 9il** [comment]
@jmh530 Do you have a use case for broadcasting API like in numir?

**Comment by jmh530** [comment]
I think of Shigeki's `broadcast` in `grain` as more like a generic version `repeat` that makes two slices the same shape. 

See below. My issue is more about usability when writing code that works for N-dimensional slices with different lengths. There are multiple options below that all cause errors. You have to `squeeze` the one slice to get it to work. Moreover, the squeezed version only works when `x` and `y` share the same first dimension (because that controls the number of rows in the byDim). If `auto x = iota(1, 3);`, then you need to figure something else out. 
```
unittest {
    import mir.ndslice.topology: iota, byDim, map, repeat, vmap, squeeze;
    import mir.ndslice.allocation: slice;
    import mir.ndslice.internal: LeftOp;
    import grain.functions.common;

    auto x = iota(2, 3);
    auto y = iota(2, 1);
    auto z = x + y; //causes error
    auto z = x.byDim!1.map!(a => a + y); //causes error
    auto z = x + y.repeat(3); //causes error
    auto z = x + y.repeat(1, 3); //causes error
    auto z = x.byDim!1.vmap(LeftOp!("+", typeof(y))(y)); //causes error
    auto z = x.byDim!1.map!(a => a + y.squeeze); //works!

    //did not check if these work, but I think they do
    auto a = broadcast(x, y);
    auto z = slice(a[0] + a[1]);
    auto z = x.broadcast(y).map!(a => a[0] + a[1]).slice;
}
```

**Comment by 9il** [comment]
>     //did not check if these work, but I think they do
>     auto a = broadcast(x, y);
>     auto z = slice(a[0] + a[1]);
>     auto z = x.broadcast(y).map!(a => a[0] + a[1]).slice;

These cases wouldn't work. 
You can use `map`/`vmap` with `fuse` and `byDim`. Or use eiger `[] = <expr with map>`, `[] op= <some expr>` operations.
