### ISSUE TITLE
Readme.md graphic typo

### ISSUE THREAD

**Issue by thewilsonator** [libmir/mir-algorithm#24]
Univarsal should be Universal.

Also the long dash - short dash lines for shape topology and subspace topology go under the ndSlice box unlike the one between Univarsal(sic) and Dynamic.

The thought bubble should have a full stop after "Any pointer is an Iterator"

**Comment by 9il** [comment]
> Univarsal should be Universal.

Fixed, thanks!

> Also the long dash - short dash lines for shape topology and subspace topology go under the ndSlice box unlike the one between Univarsal(sic) and Dynamic.

This is how it should be
