### ISSUE TITLE
`center` and precision with large values

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-algorithm#269]
This is more of a question than anything else.

The `center` function has a unitttest that shows how to use `mean` with optional sum algorithms (see [here]( https://github.com/libmir/mir-algorithm/blob/11dac273e63833207e4089cb11b156ebeae52aba/source/mir/math/stat.d#L1622)). However, it occurs to me that `1e104 - 5000` == `1e104` due to the precision of double types at that level. 

I can think of a few potential resolutions, but two strike me as the best. 

1. Adjust the function that is passed to `center` so that it has an assert to check for this. That way it can be removed in release code. The assert I would use would be modeled on what is below. 
2. Add a template bool parameter that makes the assert opt-in, so that you can make it not run even when not compiling with assert.

Regardless, I do feel that I should adjust the above UT because it is not, strictly speaking, accurate. It can at least have a message about the issue. 

Where this comes back around is that I am working on a `variance` function right now and I will not get the same value as if I am doing it by hand. 

```
/+dub.sdl:
dependency "mir-algorithm" version="*"
dependency "mir-core" version="*"
+/

import std.stdio: writeln;
import mir.ndslice.slice: sliced;
import mir.math.common;
import mir.math.ieee;

void main() {
    auto a = [1, 1e100, 1, -1e100];

    auto x = a.sliced * 10_000;
    double mu = 5000.0;
    
    foreach(e; x) {
        assert(fabs(e.nextUp - e) <= mu || fabs(e - e.nextDown) <= mu, "IEEE floating point line too spread apart at current value");
    }
}
```

**Comment by jmh530** [comment]
Something like this seems a bit better
```
static if (isFloatingPoint!(typeof(e))) {
    assert(!(e > mu && fabs(e - e.nextDown) <= mu) != !(e < mu && fabs(e.nextUp - e) <= mu),
           "IEEE floating point line too spread apart at current value");
} else static if (isComplex!(typeof(e))) {
    // todo
}
```

**Comment by 9il** [comment]
This is good unittest, it works as expected. Instead of adding a new feature, it is better to show fp behavior explicitly in the unittest. Moreover, the case you have shown is almost always valid for already centered data. So it isn't an issue, just a numeric feature.

- Add a comment to the line `auto result = [5000, 1e104, 5000, -1e104].sliced;` about FP precision.
- Use exact `==` in asserts. It is correct for this data and `kbn` like algorithms.

```d
...
    auto result = [5000, 1e104, 5000, -1e104].sliced;

    assert(x.center!(mean!"kbn") == result);
    assert(x.center!(mean!"kb2") == result);
    assert(x.center!(mean!"precise") == result);
}
```
