### ISSUE TITLE
weird rendered documentation

### ISSUE THREAD

**Issue by wilzbach** [libmir/mir-algorithm#27]
![image](https://cloud.githubusercontent.com/assets/4370550/23585023/c1cf1944-0172-11e7-897d-a0684bbb90e7.png)

http://docs.algorithm.dlang.io/latest/mir_ndslice_sorting.html

However the plain text version looks correct:

> operation $(D less). Performs $(BIGOH ndslice.elementsCount) evaluations of `less`.
Unlike `isSorted`, $(LREF isStrictlyMonotonic) does not allow for equal values,
i.e. values for which both `less(a, b)` and `less(b, a)` are false.
With either function, the predicate must be a strict ordering just like with

https://github.com/libmir/mir-algorithm/edit/master/source/mir/ndslice/sorting.d

Any ideas?

**Comment by 9il** [comment]
Because D macros system :-(

**Comment by 9il** [comment]
Probably because `isStrictlyMonotonic` has `ditto` comment

**Comment by 9il** [comment]
fixed using `_` prefix
