### ISSUE TITLE
Enhance Slice with selectLabels

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-algorithm#272]
There is an example for [slice](http://mir-algorithm.libmir.org/mir_ndslice_allocation.html#.slice) that shows how to use `Slice` `Labels` to create a dataframe. However, I do not see the functionality to `select` on the basis of labels. I propose adding a `selectLabels` function that allows the user to select a dimension (or one or more dimensions) and return sub-slice of just the data with those labels. 

For instance, `dataframe.selectLabel!1["income"]` would be equivalent to `dataframe[0 .. $, 0]` in that example.

**Comment by 9il** [comment]
Slice labels haven't been finished. They are in the initial state. Most of the ndslice code didn't know about them. The labels are aimed to be a generalized and unified replacement for [Series](http://mir-algorithm.libmir.org/mir_series.html). Its code can be used for reference to implement labels support in Slice.

`dataframe.selectLabel!1["income"]` syntax requires to make a new type.

`dataframe.selectLabel!1("income")` can be done using a method, it is preferred.

**Comment by 9il** [comment]
I don't have a plan to work on this feature in the near future. If one would like, please reopen a PR.
