### ISSUE TITLE
byDim/map with lambdas

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-algorithm#288]
The code below fails to compile because the result will be the transposed with what is expected. Trying to apply `unpack` or `transposed` simply fails for me.

```
unittest
{
    import mir.ndslice.topology: iota, byDim, map;

    auto s = iota(2, 3).byDim!1.map!(a => a * 3);
    assert(s == [[ 0,  3,  6],
                        [ 9, 12, 15]]);
}
```

**Comment by jmh530** [comment]
It looks like the issue is that the type of `s` is 
```
mir.ndslice.slice.Slice!(MapIterator!(SliceIterator!(IotaIterator!long, 1LU, cast(mir_slice_kind)0), __lambda1), 1LU, cast(mir_slice_kind)2).mir_slice
```
and `unpack` can only handle types like
```
Slice!(SliceIterator!(Iterator, M, innerKind), N, outerKind)
```
Or in other words, there is an extra shell of the `MapIterator` around the `SliceIterator`. This also occurs with `vmap`. I would imagine that longer chains would result in even more nested types.

**Comment by 9il** [comment]
This doesn’t work by Slice type design. You need either to allocate using fuse or use element wise assignment  per column

**Comment by jmh530** [comment]
Ah thanks. I tried `fuse` too, but I must have screwed something up. My actual use case was something like below. Might make a good example. 

```
unittest {
    import mir.ndslice.topology: iota, byDim, map;
    import mir.ndslice.dynamic: transposed;
    import mir.ndslice.fuse: fuse;
    import mir.ndslice.slice: sliced;
    
    auto x = [1, 2].sliced;

    auto s = iota(2, 3).byDim!1.map!(a => a * x).fuse.transposed;
    assert(s == [[ 0,  1,  2],
                        [ 6, 8, 10]]);
}
```

**Comment by 9il** [comment]
> Might make a good example.

👍

`fuse.transposed` can be replaced with `fuse!1`, the last one returns an already transposed contiguous slice.
