### ISSUE TITLE
Some dub documentation links are broken

### ISSUE THREAD

**Issue by tastyminerals** [libmir/mir-algorithm#296]
The links to [tasty-blog](https://tastyminerals.github.io/tasty-blog/) on https://code.dlang.org/packages/mir-algorithm are broken because of me :) I changed the links to the posts because I did minor updates and added a new post about pretty-printing the arrays. Sorry.

Here are the updated links:

[Multidimensional Arrays in D](https://tastyminerals.github.io/tasty-blog/dlang/2020/03/22/multidimensional_arrays_in_d.html)
[Using External D Libraries in D Scripts and Projects](https://tastyminerals.github.io/tasty-blog/dlang/2020/03/01/how_to_use_external_libraries_in_d_project.html)
[Pretty-printing D Arrays](https://tastyminerals.github.io/tasty-blog/dlang/2020/06/25/pretty_printing_arrays.html) [new]

**Comment by 9il** [comment]
Thanks! I have updated the readme, the dub page will be updated with the next release
