### ISSUE TITLE
min/maxPos & min/maxIndex issue

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-algorithm#311]
The functions `minmaxPos`, `minPos`, `maxPos`, `minmaxIndex`, `minIndex`, `maxIndex` cannot be passed types generated by applying `asSlice` to an `RCArray`.

Based on the error reports, I think the issue is that the slice is transformed using `lightScope(slice)` or `lightScope(slice).front`, but no adjustment is made to the iterator. So when passing to the `impl` functions, the iterator type of the slice does not match the type of the iterator. 

```
unittest
{
    import mir.rc.array: RCArray;
    import mir.algorithm.iteration: minmaxPos, minPos, maxPos, minmaxIndex, minIndex, maxIndex;

    static immutable a = [0.0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];

    auto x = RCArray!double(12);
    foreach(i, ref e; x)
        e = a[i];
    auto y = x.asSlice;
    auto z0 = y.minmaxPos;
    auto z1 = y.minPos;
    auto z2 = y.maxPos;
    auto z3 = y.minmaxIndex;
    auto z4 = y.minIndex;
    auto z5 = y.maxIndex;
}
```

**Comment by 9il** [comment]
`v3.9.13`
