### ISSUE TITLE
Can't use tolerance argument of pinv

### ISSUE THREAD

**Issue by John-Colvin** [libmir/mir-algorithm#312]
I think this could easily be a dmd problem, but I can't work it out right now.

```
pinv([1.0, 2, 3, 4].sliced(2, 2), 0.1)
```

```
Error: template lubeck.pinv cannot deduce function from argument types !()(Slice!(double*, 2LU, cast(mir_slice_kind)2), double), candidates are:
/home/john/.dub/packages/lubeck-1.1.8/lubeck/source/lubeck.d(754,5):        pinv(Flag allowDestroy = No.allowDestroy, Iterator, mir_slice_kind kind)(Slice!(Iterator, 2, kind) matrix, BlasType!Iterator tolerance = BlasType!Iterator.nan)
````

**Comment by John-Colvin** [comment]
workaround is to manually instantiate the template e.g. 
```
pinv!(No.allowDestroy, double*, SliceKind.contiguous)([1.0, 2, 3, 4].sliced(2, 2), 0.1)
```

**Comment by jmh530** [comment]
@John-Colvin Isn't this an issue for `lubeck`? The underlying problem is that template inference is not working in this case. It may be possible to restructure to fix.

At the very least there should be a unittest showing the use of `pinv` with a tolerance (there is not currently).

**Comment by John-Colvin** [comment]
woops, sorry wrong repo. https://github.com/kaleidicassociates/lubeck/issues/38
