### ISSUE TITLE
Description of isSlice does not match what it does

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-algorithm#321]
https://github.com/libmir/mir-algorithm/blob/6319750e5206e7e422fad51a0c17045fc546ee50/source/mir/ndslice/slice.d#L23

But the actual code is an enum bool, not `N`.

```
///
template isSlice(T)
{
    static if (is(T : Slice!(Iterator, N, kind), Iterator, size_t N, SliceKind kind))
        enum bool isSlice = true;
    else
        enum bool isSlice = false;
}
```

That being said, I see value in a function, maybe called `DimensionsOf`, that returns `N` for a `Slice` (and potentially with an overload for the number of dimensions of static/dynamic arrays).

**Comment by 9il** [comment]
Thanks!
