### ISSUE TITLE
Q (feature request): RobustScaler

### ISSUE THREAD

**Issue by mingwugmail** [libmir/mir-algorithm#322]
Hi,

I did some search, but didn't find anything related, I'm wondering does Mir have some function similar to this:

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.RobustScaler.html

or in some other D library?

Thanks.

**Comment by 9il** [comment]
RobustScaler has quite hight level API. @jmh530  is working on [mir-stat](https://github.com/libmir/mir-algorithm) library that already provides some building blocks.

Check http://mir-stat.libmir.org/mir_stat_descriptive.html in combinaitno with http://mir-stat.libmir.org/mir_stat_transform.html. Can you replace RobustScaler with them?

**Comment by jmh530** [comment]
@mingwugmail As @9il indicates, you should be able to use `transform` with `median` and `interquartileRange` to get the basic functionality, although it may not be the most efficient approach. It would be more efficient to calculate the median and the interquartileRange at the same time, which would require new functionality.

**Comment by mingwugmail** [comment]
Thanks for the info.

I close this one, and open a new one there to track:

https://github.com/libmir/mir-stat/issues/20
