### ISSUE TITLE
Indexed missing from main documentation page

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-algorithm#33]
In the main page of the documentation:
http://docs.algorithm.dlang.io/latest/mir_ndslice.html
The topology section does not mention indexed:
http://docs.algorithm.dlang.io/latest/mir_ndslice_topology.html#.indexed

**Comment by jmh530** [comment]
I also noticed that Stack is still listed there

**Comment by 9il** [comment]
Tanks! fixed
