### ISSUE TITLE
Doc improvement: np.argsort() the Mir way: using makeIndex() & indexed()

### ISSUE THREAD

**Issue by mingwugmail** [libmir/mir-algorithm#334]
Do we have a np.argsort some where in libmir?

A quick web search didn't find it.

It's a very useful function for mir to replace numpy :-)

**Comment by jmh530** [comment]
@mingwugmail I also replied on the forum with the phobos example. This can be accomplished with [makeIndex](http://mir-algorithm.libmir.org/mir_ndslice_sorting.html#.makeIndex) in mir as well.

**Comment by mingwugmail** [comment]
Thank you so much!

Can we add the example to mir doc? and specially mention it as: "np.argsort: the mir way"

I copy & pasted the code below, so other people when they search 'argsort',  they can found it right here :-)

```
import std.algorithm.sorting: makeIndex;
import std.algorithm.comparison: equal;
import std.range: indexed;

void main() {
    int[] arr0 = [ 2, 3, 1, 5, 0 ];
    int[] arr1 = [ 1, 5, 4, 2, -1 ];

    auto index = new int[arr0.length];
    makeIndex!("a < b")(arr0, index);
    assert(index == [4, 2, 0, 1, 3]);
    auto view = arr1.indexed(index);
    assert(view.equal([-1, 4, 1, 5, 2]));
}
```

**Comment by jmh530** [comment]
@mingwugmail PRs are welcome ;)

**Comment by mingwugmail** [comment]
I indeed have thought about create a doc about numpy the Mir way doc, will do when I have time.

**Comment by jmh530** [comment]
@mingwugmail While I think that is worthwhile (include reference to the numir package), I was thinking of something less time-consuming. That is, a PR that adds a similar UT as I describe above (adjusted to work with mir) and add a link in a "See also" section to numpy's argsort.

**Comment by jmh530** [comment]
@mingwugmail Done.

**Comment by 9il** [comment]
Thank you @jmh530

**Comment by jmh530** [comment]
@9il No problem. Probably could tag a new version when the CI passes again.

**Comment by 9il** [comment]
done
