### ISSUE TITLE
Move mir.exception and mir.format to mir-core or another sperate mir library

### ISSUE THREAD

**Issue by Zardoz89** [libmir/mir-algorithm#348]
Move mir.exception and mir.format to mir-core or another separate mir library. So can be used without needing to add the whole Mir algorithm dependency by third party libraries & projects.

**Comment by 9il** [comment]
Formatting floating point numbers requires 6000 LOC big integer code that is based on mir-ndslice. It isn't something trivial for mir-core.

mir-algorithm is a big, but it is a generic D library. It is very fast to compile because almost everything is generic and it means nothing to compile.

**Comment by Zardoz89** [comment]
I'm only interested on true nogc exceptions. I said mir.format, because mir.exception have a dependency on mir.format.

**Comment by 9il** [comment]
done
