### ISSUE TITLE
Base64 (en|de)coding support

### ISSUE THREAD

**Issue by hatf0** [libmir/mir-algorithm#369]
This will serve as a general roadmap on where we are (in terms of getting this feature in).

As part of getting this feature in, I'm considering going beyond just a naive implementation -- Base64 is a fairly trivial concept, but can greatly benefit from implementing processor-specific SIMD intrinsics (this is not a novel area -- several libraries already accelerate Base64 this way). According to http://0x80.pl/notesen/2016-01-12-sse-base64-encoding.html, the author saw around a ~3-4x improvement in encoding performance by switching to a solution utilizing AVX2 / loop unrolling.

Seeing how one of the use cases of this library will be in Mir Ion, where we can have potentially (mega|giga)bytes of data encoded within a single blob object, this is a very desirable performance increase.

**Comment by 9il** [comment]
We don't need any kind of SIMD support. Please use a simple algorithm. If (mega|giga)bytes will be encoded in binary Ion, which doesn't use base64.

**Comment by hatf0** [comment]
Understood. That greatly simplifies it then!
