### ISSUE TITLE
Change signature of StringMap.findIndex

### ISSUE THREAD

**Issue by nordlow** [libmir/mir-algorithm#381]
I recommend changing signature of

```bool findIndex()(scope const(char)[] key, ref size_t index)```

to

```size_t findIndex()(scope const(char)[] key)```

that returns `this.length` upon failure. That's the common way of packing search miss state into the index.

I can do this adjustment if approved.

**Comment by 9il** [comment]
> `size_t findIndex()(scope const(char)[] key)`

This will work a bit slower because of few additional checks. The function is assumed to be inlined.
