### ISSUE TITLE
Joint allocation of StringMap array fields

### ISSUE THREAD

**Issue by nordlow** [libmir/mir-algorithm#383]
Have it been considered making the storage of keys, values, and indices use a common block allocation? That's likely gonna lead to significant speedups during construction. And what about std.experimental.allocator? Using, for instance, a free-list-over-region allocator for all StringMap-allocations in a json-tree is gonna likely gonna result in an even greater speedup. If you're interested I can add that for you.

**Comment by 9il** [comment]
That wouldn't be a great I think because extension and removal operation would become too slow.
