### ISSUE TITLE
Slice!( RCI!T, N, kind) and static pack.

### ISSUE THREAD

**Issue by aferust** [libmir/mir-algorithm#389]
Hi Ilya,

Thank you for your awesome work. Considering the below code from dcv, I want staticPack to accept Slice!( RCI!T, N, kind) and return Slice!( RCI!( T[CH] ), N-1, kind). RCArray's _payload and context are package members, so one cannot alter them (they should not be altered, I see).

For a Slice!(RCI!T, N, kind), I can access slice.iterator._array and slice.iterator._iterator, but I cannot do much with them like casting. Of course, I could do those type conversions with expensive copies. But, obviously, it would be better if it can be done without any copy. An implementation like RCArray!T.opCast() to RCArray!(T[N]) would solve this because "struct mir_rci(T)" has already this(RCArray!T array).  I appreciate any help.

Thanks in advance!
Ferhat

```d
auto staticPack(size_t CH, SliceKind kind, size_t N, Iterator)(Slice!(Iterator, N, kind) slice)
        if (N == 3LU)
    {
        alias T = DeepElementType!(typeof(slice));

        //  is(Iterator == RCI!T)
        
        // How to modify the below code ?

        size_t[N-1] shape = slice.shape[0 .. N-1];
        T[CH]* ptr = cast(T[CH]*)slice._iterator;
        alias Ret = Slice!(T[CH]*, N-1, kind);  // this should be Slice!( RCI!( T[CH] ), N-1, kind)
        return Ret(shape,  ptr);
    }

    /// ditto
    auto staticUnpack(size_t CH, SliceKind kind, size_t N, Iterator)(Slice!(Iterator, N, kind) slice)
        if (N == 2LU)
    {
        //  is(Iterator == RCI!(T[CH]))

        alias T = DeepElementType!(typeof(slice));
        
        // How to modify the below code ?

        size_t[N+1] shape = [slice.shape[0], slice.shape[1], CH];
        T* ptr = cast(T*)slice._iterator;
        alias Ret = Slice!(T*, N+1, kind); // this should be Slice!( RCI!T, N+1, kind)
        return Ret(shape, ptr);
    }
```

**Comment by 9il** [comment]
`RCI` is based on `RCArray`, this kind of cast isn't possible by design. The size of elements should be the same.

You would need either to reallocate all data or use `lightScope` view and work with it holding the RCI slice somewhere.

**Comment by aferust** [comment]
Thanks for the clarification. I will evaluate those.
