### ISSUE TITLE
Cannot grow a heap created over a range

### ISSUE THREAD

**Issue by andrewlalis** [libmir/mir-algorithm#393]
I'm trying to use Mir's binary heap structure (instead of the phobos implementation) because it allows me to access the internal `_store`, but I am running into an issue where no matter what store I provide, I'm not able to insert more elements into the heap.

For example:
```d
Object[] objects;
BinaryHeap!("a < b", Object[]) heap = heapify(objects);
heap.insert(new Object()); // <-- doesn't work!
```

The same issue occurs when using the stdlib `Array` container. I don't understand why the heap cannot be grown, when the documentation states that it should allow it, if the given store supports `insertBack`.

**Comment by 9il** [comment]
The following unittest passes in the current version:
```
@system nothrow unittest
{
    import std.container.array : Array;

    Array!int elements = [1, 2, 10, 12];
    auto heap = heapify(elements);
    assert(heap.front == 12);
    heap.insert(100);
    assert(heap.front == 100);
    heap.insert(1);
    assert(heap.front == 100);
}
```

The overload for `Object[]` isn't supposed to work because Mir's implementation is targeting to @nogc usage.

On the other hand a MR that will add a method like `insertWithGC`will be accepted.

**Comment by 9il** [comment]
That test passes as well.

```d
@system version(mir_test) unittest
{
    import std.container.array : Array;

    Array!Object elements;
    auto heap = heapify(elements);
    Object obj;
    heap.insert(obj);
}
```

**Comment by andrewlalis** [comment]
Ah okay, so it must be a store with a deterministic memory usage. Thanks for the clarification.
