### ISSUE TITLE
Changing values when combining zip/map with 2-d slice

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-algorithm#399]
In the code below, the second zip/map code causes the first part of the RefTuple to change for some non-obvious reason. When I run sum on the first value, it seems to return the right value, but when I actually check the values of the result it does not match what it should. I thought at first that it was some kind of overflow, but the value I see is between int/uint.max and long/ulong.max. 

```
import mir.ndslice.topology: iota, map, zip;
import mir.math.sum: sum;

void main()
{
    auto x = iota(2, 3);
    auto y = iota([2, 3], 1);
    auto combine1 = x.zip!true(y).map!("b");
    auto combine2 = x.zip!true(y).map!("b", "a * b").map!(a => a[0]);

    assert(combine1.sum == 21);
    assert(combine2.sum == 21);
    assert(combine1[0][0] == 1);
    assert(combine2[0][0] == 1); //fails?
}
```

**Comment by 9il** [comment]
Fixed with [mir-core](https://code.dlang.org/packages/mir-core) 1.1.105

**Comment by 9il** [comment]
The reworked version: mir-algorithm `v3.12.36` and mir-core 1.1.106.
