### ISSUE TITLE
Public imports in documentation

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-algorithm#401]
D issue [10665](https://issues.dlang.org/show_bug.cgi?id=10665) fixes the problem of public imports not showing up in documentation. However, the documentation for the `mir` projects do not seem to have the public imports listed currently.

**Comment by 9il** [comment]
Likely we need to update the docker image with the compiler.

**Comment by hatf0** [comment]
This is actually correct behavior: see [here](https://github.com/dlang/dmd/pull/10365). Documentation isn't emitted for plain public imports, they're only emitted if they have a DDoc comment associated with them. You can see this working properly [here](http://mir-core.libmir.org/mir_utility.html#._expect) where the public import is actually annotated: https://github.com/libmir/mir-core/blob/87fea6c28223ed5ad46a3c97b2282fcfc736f193/source/mir/utility.d#L28-L32

**Comment by jmh530** [comment]
@hatf0 Ah, ok. Thanks for confirming.
