### ISSUE TITLE
Compilation error when passing nested Slice to fuse function

### ISSUE THREAD

**Issue by lempiji** [libmir/mir-algorithm#409]
Code that used to work, but does not compile in the latest version. Perhaps this is a regression.

reproduction code

```
auto m = [1,2,3,4,5,6].sliced(2,3).pack!1.fuse();
```

error

```
...\AppData\Local\dub\packages\mir-algorithm-3.12.47\mir-algorithm\source\mir\ndslice\fuse.d(326,29): Error: mismatched array lengths, 1 and 2
```

**Comment by 9il** [comment]
This is unlikely is supposed to work. It may work before, however, the use case isn't clear.

```d
auto m = [1,2,3,4,5,6].sliced(2,3).pack!1.unpack.slice;
```

Would work much better. In addition, it cab reduced to just:


```d
auto m = [1,2,3,4,5,6].sliced(2,3).pack!1.unpack;
```

Please let me know your use case if it isn't solved for you.

**Comment by lempiji** [comment]
Thanks for the quick reply.
The broken part is this: it would be nice to be able to unpack, but there is a map right before it, so I get an error.

https://github.com/lempiji/golem/blob/master/source/golem/math.d#L1676

**Comment by lempiji** [comment]
It's all fixed! Thank you!
