### ISSUE TITLE
[feature request] Add numpy.genfromtxt()

### ISSUE THREAD

**Issue by mw66** [libmir/mir-algorithm#442]
https://forum.dlang.org/thread/recgifvrlcambwwkoobx@forum.dlang.org

Hi,

I'm just wondering what is the best way to read CSV data file into Mir (2d array) ndslice? Esp. if it can parse date into int/float.

I searched a bit, but can't find any example.

Thanks.

So, can we add numpy.genfromtxt():

https://numpy.org/doc/stable/reference/generated/numpy.genfromtxt.html

Esp. with column converters?

**Comment by mw66** [comment]
https://github.com/Kriyszig/magpie

BTW, found this for the reference:

from_csv(string path, int indexDepth = 1, int columnDepth = 1,int[] columns = [], char sep = ',')

**Comment by mw66** [comment]
For Mir to catch up with numpy, being able to easily read CSV to import data is a must to attract data scientists.

In numpy/pandas, it's just one liner.

**Comment by 9il** [comment]
[mir-ion](https://github.com/libmir/mir-ion) can deserialize Mir and common 2D arrays from Binary Ion, Text Ion, JSON, MsgPack. Plus YAML support is coming soon.

We just need to add CSV there.

```
void serializeFromCsv(S)(scope ref S serializer, scop const(char)[] csv, /+ other params+/)
{
///on the fly
 /// - parse csv

 /// - recognise  cell patters: integers, floats, timestamps, true, false, null; all others are strings
 /// - serializer.putValue(value)
}
```

 - The serialiser interface is here. https://github.com/libmir/mir-ion/blob/master/source/mir/ser/interfaces.d#L18
 - `[Timestamp](http://mir-algorithm.libmir.org/mir_timestamp.html).fromYamlString` and `Timestamp.fromString` have recognition API 
 - For `long` and `double` recognition  [fromString ](http://mir-algorithm.libmir.org/mir_parse.html#.fromString.2)

If we have this function implemented I will do the rest. The API will looks like:

```d
auto matrix = deserializeCsv!(Slice!(2, double*));
```

**Comment by jmh530** [comment]
I don't really have a good sense of how to use `mir.ion`. I see that it references a cookbook, but it would be good to have a simple example written in D on the readme.md.

**Comment by jmh530** [comment]
> ```d
> auto matrix = deserializeCsv!(Slice!(2, double*));
> ```

Am I correct that the `deserializeCsv` would handle the transformation of what is read from a `.csv` file into the `Slice` type? It wouldn't handle the reading of the file itself.

**Comment by 9il** [comment]
The fixed version should looks like:
```d
auto matrix = csvText.deserializeCsv!(Slice!(2, double*));
```

`deserializeCsv` will call `serializeFromCsv` to serialize CSV to binary Ion DOM (it is super fast), and then, it will call `deserializeValue`, which is already implemented.

Mir always splits deserializ=sation logic in two stages: First, data to binary Ion; second, binary ion to value.

The idea is that binary ion to value works fast and unified across all types of formats.

**Comment by 9il** [comment]
Assume raw major notation.

Then CSV should have the following options to be converted to Ion:
 - matrix
 - an array of records with inner keys in the first raw
 - a record of arrays with outer keys in the first column
 - a record of record with inner keys in the first raw and outer keys in the first column

These four kinds of conversion kinds allow converting CSV to Ion on the fly.

Also, a simple transposition with full memory allocation will allow other three conversions:
 - transposed matrix
 - an array of records with inner keys in the first column
 - a record of arrays with outer keys in the first raw
 - a record of record with inner keys in the first column and outer keys in the first raw

We can define CSV algebraic as follow:
```d
module mir.algebraic_alias.csv;
/++
Definition union for $(LREF JsonAlgebraic).
+/
import mir.algebraic;
/++
CSV tagged algebraic alias.
+/
alias CsvAlgebraic = Algebraic!Csv_;

union Csv_
{
    /// Used for empty CSV scalar like one between two separators: `,,`
    typeof(null) null_;
    /// Used for false, true, False, True, and friends. Follows YAML conversion
    bool boolean;
    ///
    long integer;
    ///
    double float_;
    ///
    immutable(char)[] string;
}
```

**Comment by 9il** [comment]
```d
/++
DRAFT:

Then CSV should have the following options to be converted to Ion:
 - matrix
 - an array of records with inner keys in the first raw
 - a record of arrays with outer keys in the first column
 - a record of records with inner keys in the first raw and outer keys in the first column

These four kinds of conversion kinds allow converting CSV to Ion on the fly.

Also, a simple transposition with full memory allocation will allow other four conversions:
 - transposed matrix
 - an array of records with inner keys in the first column
 - a record of arrays with outer keys in the first raw
 - a record of records with inner keys in the first column and outer keys in the first raw
+/
module mir.csv;

///
struct Csv
{
    ///
    const(char)[] text;
    ///
    char sep = ',';
    ///
    bool header = false;
    ///
    bool columnIndex = false;

    void serialize(S)(scope ref S serializer) scope const
    {
        // TODO
    }
}

struct TranposedCsv
{
    ///
    Csv csv;

    void serialize(S)(scope ref S serializer) scope const
    {
        import mir.algebraic_alias.csv: CsvAlgebraic;
        import mir.ndslice.slice: Slice;
        import mir.rc.array: RCI;
        import mir.ion.conv: serde;
        import mir.ser: serializeValue;

        alias CsvMatrix = Slice!(2, RCI!CsvAlgebraic*);
        auto matrix = csv.serde!CsvMatrix;
        auto scopeMatrix = matrix.lightScope;
        serializer.serializeValue(scopeMatrix);
    }
}

/// matrix and transposed matrix
unittest
{
    import mir.ndslice.slice;
    import mir.ion.conv: serde;

    auto text = "1,2\n3,4";
    auto matrix = text.Csv.serde!();
    assert(matrix == [[1, 2], [3, 4]]);

    matrix = text.Csv.TranposedCsv.serde!(Slice!(2, int*));
    assert(matrix == [[1, 3], [2, 4]]);
}

/// Matrix
unittest
{
    import mir.ndslice.slice;
    import mir.ion.conv: serde;

    auto text = "1,2\n3,4";
    auto matrix = text.Csv.serde!();
    assert(matrix == [[1, 2], [3, 4]]);

    matrix = text.Csv.TranposedCsv.serde!(Slice!(2, int*));
    assert(matrix == [[1, 3], [2, 4]]);
}

/++
With header
+/
unittest
{
    // TODO
}

/++
With column index
+/
unittest
{
    // TODO
}

/++
With header and column index
+/
unittest
{
    // TODO
}

```

**Comment by 9il** [comment]
Added draft: https://github.com/libmir/mir-ion/blob/master/source/mir/csv.d

**Comment by jmh530** [comment]
I don't know if this applies or not, but one thing that is very useful in R's `read.csv` [1] function is the ability to identify certain strings as representing NAs. So for instance, setting it so that "NA" or "N/A" or "#N/A" (you could even do -999) are known as NAs, then the entire column will be the floating point type even if there were originally some strings in it. It makes it so you don't need to read the column as a string and process it later. 

Not sure what other features that would be useful, but that's one that sticks out. 

[1] https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/read.table

**Comment by mw66** [comment]
Also check numpy.genfromtxt() and pandas.read_csv().

I think handle invalid nan, and allow user pass in column converters callbacks are two most important features.

numpy.genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+, -./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes', *, ndmin=0, like=None)[[source]](https://github.com/numpy/numpy/blob/v1.23.0/numpy/lib/npyio.py#L1683-L2416)



https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

**Comment by mw66** [comment]
> column converter callbacks

E.g. user can plug in his own date string to int/float converter function.

**Comment by 9il** [comment]
@mw66 I can't see a reason why we may even need to provide an in-column converter callback while we have the power of `mir.algebraic`, `mir.ndslice`, and `mir.functional`. It may be confusing but the experience of people from scripting languages are and mine are so different that it hard to get why the want to do something one way while there is a 'common' way to do it.

Maybe we could share our experiences with each other.

Let's do the following. Please provide a CSV/TSV data sample and an example in any programming language of how you handle it. Then I will provide an example of how we can handle the data in Mir. When we do so it would be easy to figure out a good API.

**Comment by 9il** [comment]
@mw66 I have updated the [draft](https://github.com/libmir/mir-ion/blob/master/source/mir/csv.d) with callback support. Please check the first unittest.

**Comment by mw66** [comment]
>  why we may even need to provide an in-column converter callback

The reason is simple: the ndslice's type is homogeneous, it's just double/float, but the input can be mixed with date: e.g.

```
Date,Open,High,Low,Close,Volume
2021-01-21 09:30:00,133.8,134.43,133.59,134.0,9166695
2021-01-21 09:35:00,134.25,135.0,134.19,134.5,4632863
```
You need the converter at import time, to convert the date *string* into double, not afterwards (how do you store string in the ndslice mixed with floats then)?

**Comment by mw66** [comment]
https://github.com/libmir/mir-ion/blob/master/source/mir/csv.d#L518

So, ndslice can have mixed types for different columns? (sorry if I miss something, I'm a newbie to mir).

**Comment by 9il** [comment]
> So, ndslice can have mixed types for different columns? (sorry if I miss something, I'm a newbie to mir). 

No, ndslice can't. However, you aren't limited to having ndslice matrix of double. Five other options in Mir can do it:

 - WIP `Series!(Timestamp*, double*, 2)` support: `mir.series` (mir-algorithm) can store the index of one type and a ndslice data matrix of another type. `mir-csv` will be able to load the index from the first column.
 - Implemented `Slice!(CsvAlgebraic*, 2)` support: `mir.algebraic.Algebraic` (mir-core) including `mir.aligebraic_alias.csv` (mir-ion) can store value of different type. So, you could load a ndslice matrix of algebraic types and then process it. 
 - Implemented `Tuple!(Timestamp[], double[], double[], double[], double[], double[])`: `mir.functional.Tuple` (mir-core, latest release), which is used in the [example](https://github.com/libmir/mir-ion/blob/master/source/mir/csv.d#L518), is a kind of static array of different predefined types.
 - A struct of arrays:
```d
import mir.timestamp: Timestamp;
import mir.serde: serdeKeys;
struct Data
{
    @serdeKeys("Date")
    Timestamp[] date;

    @serdeKeys("Open")
    double[] open;
    ...
}
 ```
- Associative arrays of columns: `CsvAlgebraic[][string]`

And the callback for column conversion is implemented as you wanted.

**Comment by jmh530** [comment]
I would want to do something like this:
```d
auto text = "1,2\n3,4\n5,#N/A\n";
auto matrix = //TODO
matrix.should == [[1.0, 2], [3.0, 4], [5.0, double.nan]];
```
I saw something with nulls in your UT, but I didn't think you could mix nulls with other data in an array. 

With respect to column converters/classes, I think that is just a scripting language way to try to enforce types. It's telling the function how to process the text from the csv. For a scripting language it is good to have it when you need it, but if you have a type system then usually you would just tell it that it is a particular type (provided that type is supported). 

I think one difficulty is that this involves a lot of different functionality that don't have the best documentation or examples. Even if it is incredibly powerful, more work on that front may help reduce the burden on future users.

**Comment by 9il** [comment]
> I saw something with nulls in your UT, but I didn't think you could mix nulls with other data in an array.

`mir.ion.conv.serde!(mir.algebraic.Nullable!double[][])(text.Csv)`

**Comment by 9il** [comment]
>> I saw something with nulls in your UT, but I didn't think you could mix nulls with other data in an array.
> mir.ion.conv.serde!(mir.algebraic.Nullable!double[][])(text.Csv)

@jmh530 
The full example
```d
auto text = "1,2\n3,4\n5,#N/A\n";
auto matrix = text.Csv.serde!(Slice!(Nullable!double*, 2))
    .map!(visit!((double x) => x, (_) => double.nan);
matrix.should == [[1.0, 2], [3.0, 4], [5.0, double.nan]];
```

**Comment by mw66** [comment]
> > why we may even need to provide an in-column converter callback
> 
> The reason is simple: the ndslice's type is homogeneous, it's just double/float, but the input can be mixed with date _string_: e.g.
> 
> ```
> Date,Open,High,Low,Close,Volume
> 2021-01-21 09:30:00,133.8,134.43,133.59,134.0,9166695
> 2021-01-21 09:35:00,134.25,135.0,134.19,134.5,4632863
> ```
> 
> You need the converter at import time, to convert the date _string_ into double, not afterwards (how do you store string in the ndslice mixed with floats then)?

BTW, here is the Python code, the converter is a dictionary keyed by column index/name:
```
import numpy as np
from datetime import datetime

str2date = lambda x: datetime.strptime(x, '%Y-%m-%d %H:%M:%S')

data = np.genfromtxt('data.csv',dtype=None,names=True, delimiter=',', converters = {0: str2date})
```

**Comment by mw66** [comment]
> For a scripting language it is good to have it when you need it, but if you have a type system then usually you would just tell it that it is a particular type (provided that type is supported).

Without converters in D, then how do you handle the date string in my above example?

**Comment by 9il** [comment]
> Without converters in D, then how do you handle the date string in my above example?

`mir.csv` recognise it is a timestamp. It do it for all input fields: it parses numbers, booleans and timestamps.

**Comment by mw66** [comment]
> > Without converters in D, then how do you handle the date string in my above example?
> 
> `mir.csv` recognise it is a timestamp. It do it for all input fields: it parses numbers, booleans and timestamps.

Then it's in fixed format, but in *real life* data you may encounter all kinds of formats e.g:
```
2022/09/24
2022.09.24
2022-09-24
09/24/2022
09 24 2022
09/24/22
...
...
The list can  go on and on
```

You'd better allow user to plug in his own converters for his own data.

**Comment by 9il** [comment]
> You'd better allow user to plug in his own converters for his own data.

It is allowed now. Please check the `conversionFinalizer`.

**Comment by mw66** [comment]
> > You'd better allow user to plug in his own converters for his own data.
> 
> It is allowed now. Please check the `conversionFinalizer`.

```
conversionFinalizer : (
            unquotedString,
            scalar,
            columnIndex,
            columnName)
```

So you pass in columnIndex and  columnName to let the user branch in his function to dispatch to different columns? This looks ugly.

Why not use the Python dictionary format, and let the Mir do such branching in the library?

**Comment by 9il** [comment]
It is less verbose in Python because it is a scripting language. If you think it will be less verbose please give an example in D. But this should be a full-featured solution like the current one.

**Comment by mw66** [comment]
It has nothing to do with Python being a scripting language. It's about the api function interface, and who (the lib or the user) is responsible for the column converters dispatching.

Example in D can just follow the Python api example:
```
  data1 = np.genfromtxt("data1.csv", ...,  [1: cvtr1, 2: cvtr2]);  // D does not have named arg yet, let just use positional arg
  data2 = np.genfromtxt("data2.csv", ...,  [2: cvtr1, 1: cvtr2]);
```

So why this code cannot be implemented in the D library?

**Comment by 9il** [comment]
It can be added. But that isn't generalised solution. We could do an additional overload like that. Note, that this can be just a wrapper around the _verbose_ the solution.

**Comment by mw66** [comment]
1) I don't understand what you mean by "that isn't generalised solution", can you elaborate? I think passing the dictionary is as general as the current `conversionFinalizer`.

2) please do the overload. As long as the dispatching is inside the library code, the user calling code will be tidy and succinct.

**Comment by 9il** [comment]
> * I don't understand what you mean by "that isn't generalised solution", can you elaborate? I think passing the dictionary is as general as the current `conversionFinalizer`.

`conversionFinalizer` provides much more context for user.

**Comment by mw66** [comment]
> > * I don't understand what you mean by "that isn't generalised solution", can you elaborate? I think passing the dictionary is as general as the current `conversionFinalizer`.
> 
> `conversionFinalizer` provides much more context for user.

OK. But in my experience (as a data scientist role), I've never found I need that context. People are happy with the current converters dictionary solution that is in both `numpy.genfromtxt()` and `pandas.read_csv()`, and I never heard other people complain it's too restricted.

The converters dict is succinct, and also make users from numpy & pandas feel at home, and make the transition process to Mir easier.

**Comment by jmh530** [comment]
I think it’s good to have all these tools laid out, but it could be good to
add a readCSV or equivalent function to minor in order to handle common use
cases.
