### ISSUE TITLE
filter and each compiler error

### ISSUE THREAD

**Issue by fabienmica** [libmir/mir-algorithm#448]
I have got a compile error when using filter together with each

```
import mir.algorithm.iteration: each, filter;
import mir.ndslice.topology : map;
    
//Does not compile
 [1, 2, 3].filter!(x=>x>=2)
          .each!(x=>writeln(x));

 //Compile
 [1, 2, 3].map!(x=>2*x)
          .each!(x=>writeln(x));
```

`Error: none of the overloads of template `mir.primitives.anyEmpty` are callable using argument types `!()(Filter!(__lambda1, Slice!(int*, 1LU, mir_slice_kind.contiguous)))``

**Comment by jmh530** [comment]
Below is `anyEmpty` from `mir.primitives`. The body of the function allows for the `Range` to have `anyEmpty` or `shape` and then falls back to empty. However, the template constraint does not allow for that. Maybe an additional check that the range can call empty would resolve this issue.

```d
bool anyEmpty(Range)(scope const auto ref Range range) @property
    if (hasShape!Range || __traits(hasMember, Range, "anyEmpty"))
{
    static if (__traits(hasMember, Range, "anyEmpty"))
    {
        return range.anyEmpty;
    }
    else
    static if (__traits(hasMember, Range, "shape"))
    {
        return anyEmptyShape(range.shape);
    }
    else
    {
        return range.empty;
    }
}
```

**Comment by jmh530** [comment]
Fixed after https://github.com/libmir/mir-algorithm/pull/456
