### ISSUE TITLE
mir.allocators: betterC allocators

### ISSUE THREAD

**Issue by 9il** [libmir/mir-algorithm#49]
We need to rework std.exprimental.allocators to be betterC.

**Comment by n8sh** [comment]
@9il What is it about the allocators in std.exprimental.allocators that needs to be changed to make them non-betterC? Is the problem all of them or just some?

**Comment by 9il** [comment]
All Mallocator like allocators should be a structs with generic types . Currently we need to link Phobos to write nogc allocators, it is weird.

**Comment by 9il** [comment]
I mean with generic methods.

**Comment by 9il** [comment]
In addition their instance method should return a value (not ref) or the structs should be a generic types.

**Comment by 9il** [comment]
No plan for now

**Comment by 9il** [comment]
Added betterC update for https://github.com/dlang-community/stdx-allocator
