### ISSUE TITLE
byElement was replaced by?

### ISSUE THREAD

**Issue by timotheecour** [libmir/mir-algorithm#51]
@9il 
`git log -SbyElement` shows eb7b255cf78ee6a2f1b420ae620a0e428f748fb6 but this doesn't seem to show the corresponding replacement

EDIT:
is that : `a.byElement` => `a.iterator` ?

**Comment by 9il** [comment]
Does [flattened](http://docs.algorithm.dlang.io/latest/mir_ndslice_topology.html#.flattened) work for you?

**Comment by 9il** [comment]
> is that : a.byElement => a.iterator ?

No, it is `flattened`.

**Comment by timotheecour** [comment]
* @9il flattened doesn't look like a drop-in replacement:

```
# before breaking changes: this worked:
auto a1=some_slice.byElement.array;

#after breaking changes:
auto a2=some_slice.flattened.array; // CT error: emplate std.array.array cannot deduce function from argument types !()(Slice!(cast(SliceKind)2, [1LU], Result)), candidates are ...

# this works though:
auto a3=some_slice. iterator.array;
```

* Any disadvantage to using `iterator` over `flattened` ?

* How about adding to a `release_notes.md` section every time you make breaking changes to help users upgrade their code?

**Comment by 9il** [comment]
> auto a2=some_slice.flattened.array; // CT error: emplate std.array.array cannot deduce function from argument types !()(Slice!(cast(SliceKind)2, [1LU], Result)), candidates are ...

This should work. Please open a detailed issue with complete code sample, compiler version, mir-algorithm version and dub.json.

> Any disadvantage to using iterator over flattened ?
> # this works though:
> auto a3=some_slice. iterator.array;

This should NOT work. ditto (new issue).

**Comment by 9il** [comment]
> How about adding to a release_notes.md section every time you make breaking changes to help users upgrade their code?

I will do it for breaking changes inside new API.

**Comment by 9il** [comment]
`!()(Slice!(cast(SliceKind)2, [1LU], Result))` - you are doing something wrong!
What is `Result`? It must be an iterator, not a range. If you are trying to create a slice on top of range, use `slicedField`, not `sliced`.

**Comment by 9il** [comment]
New ndslice API is based on top of iterators.

**Comment by timotheecour** [comment]
ok, after upgrading to more recent releases, `flattened` indeed works; thanks!
