### ISSUE TITLE
allow `_` to mean `0..$` ; allow strideed indexing `R(a, b, s)` for numpy's a:b:s

### ISSUE THREAD

**Issue by timotheecour** [libmir/mir-algorithm#53]
## allow `_` for `0..$`

in a tensor library i've worked on I defined `_` to mean `0..$`
it worked as intended. Would be nice to support that in mir to make user code more readable.

## implementation wise, it was something like:

```
enum _=R();

struct R {
  uint a0 = 0; ///from
  uint a1; ///to
  int stride = 1; ///stride
  bool is_a1_end = true; ///when is_a1_end=true, a1 should be $
  this(T1)(T1 stride) {
    this.stride = cast(int) stride;
  }

  this(T1, T2)(T1 a0, T2 a1) {
    this.a0 = cast(uint) a0;
    this.a1 = cast(uint) a1;
    is_a1_end = false;
  }

  this(T1, T2, T3)(T1 a0, T2 a1, T3 stride) {
    this(a0, a1);
    this.stride = cast(int) stride;
  }
}

```

and opIndex overloaded to take `R` arguments.
 
## strided indexing
This allowed things like:
`slice[0, _, R(2, $, 2), R(0, $, -1), ]`

**Comment by 9il** [comment]
This is syntax sugar. Please create a DIP for new language addition.

The code may look something like that:
```
slice[0, .., 2 .. $ .. 2, @ 0 .. $ .. 1]
```

The good style is to allow only positive strides. Ans use a special syntax to reverse the order. It will work faster and allows to replace `-1` with `ReversedIterator` in some cases.

**Comment by jmh530** [comment]
I'm 100% in favor of this.

**Comment by timotheecour** [comment]
@jmh530 in favor of what? that was ambiguous :)

> This is syntax sugar. Please create a DIP for new language addition.

What I proposed requires no D language addition, so can be implemented without waiting for a language addition that could take a long time to materialize (if at all). If and when it becomes available mir can start using it to improve syntax, but is not necessary.

> `slice[0, .., 2 .. $ .. 2, @ 0 .. $ .. 1]`

This would require language addition as `..` can't be used like that, neither can `@`.

So I would be in favor of building on what D offers to improve slicing syntax; whether it's the syntax I proposed above or any other D valid syntax. If future D allows better, great, but shouldn't depend on that.

> The good style is to allow only positive strides. Ans use a special syntax to reverse the order. It work faster and allows to replace -1 with ReversedIterator in some cases.

Both matlab and numpy and other support positive and negative strides; is your concern that supporting negative strides should not affect performance for positive strides? 
This can be done by distinguishing on the type of the stride (but there are other ways):

```
slice[a..b] // current: assumes stride=1
slice[R(a,b,-1)] // proposed: assumes stride=-1
slice[R(a,b,uint(2))] // proposed: assumes stride=2, compiler knows it's a positive stride
```

**Comment by jmh530** [comment]
@timotheecour My first preference is the DIP/language change the Ilya suggests. However, I recognize your point that it might be difficult. Thus, I also favor adding _ as an overload to opSlice/opIndex. 

My feelings on the other R(a, b, s) are not as strong. Obviously, if D had 0..2..$, then that would also be nice, but R is a little ugly. 

I'm also not a fan of `@` and would prefer instead something like
`slice[0, .., 2 .. 2 .. $, $ .. -1 .. 0]`

**Comment by jmh530** [comment]
Andrei commented on at least part of the `..` notation on the forum. He seemed quite against it. 
https://forum.dlang.org/post/opu5as$geo$2@digitalmars.com
