### ISSUE TITLE
Conversion from mir slice to an array

### ISSUE THREAD

**Issue by dataPulverizer** [libmir/mir-algorithm#56]
Hi,

I would like to be able to convert a mir slice object back into an array, I have looked in the documentation but cannot find a function that allows this - perhaps I have missed it.

**Comment by 9il** [comment]
Hi,
For contiguous slices on top of a pointer `.field`](http://docs.algorithm.dlang.io/latest/mir_ndslice_slice.html#.Slice.field) property can be used. It does not reallocate memory. Other slices can be reallocated first using `slice` or `makeSlice`, the result of reallocation would a contiguous slice on top of a pointer.
