### ISSUE TITLE
Sweeping across arrays

### ISSUE THREAD

**Issue by dataPulverizer** [libmir/mir-algorithm#58]
Is it possible to "sweep" a vector across a 2-D array for instance subtracting a vector from each "column" of a 2-D array using Mir? The example in R would be:
```
x = matrix(1:50, nc = 5, byrow = TRUE); y = matrix(1:10, nc = 1); x; y
sweep(x, 1, y, FUN =  "-")
```

**Comment by jmh530** [comment]
R's apply is a related functionality (being able use a function like sum or mean by column or by row). 

This reminds me of some of the discussion that had led to issue [#46](https://github.com/libmir/mir-algorithm/issues/46). The difference would be that one would be cutting by dimension, rather than within a dimension.

**Comment by dataPulverizer** [comment]
R's `sweep()` function is certainly similar to its `apply()` function but as you said usually used for aggregation over all but specified dimensions. I think having functionality similar to R's multi-dimensional `sweep()` and `apply()` functions would be very useful if this is not already available in Mir.

**Comment by jmh530** [comment]
@dataPulverizer I agree wholeheartedly.

**Comment by jmh530** [comment]
@dataPulverizer It may be possible to get something like `apply` working with mir.ndslice.chunks. 

I'm using 0.6.6, which does not yet have it, but I would think that something like below (as a rough sketch) might work. 

```
auto apply(alias f, size_t dim)(Slice slice)
{
    import mir.ndslice : chunks, map;
    return slice.chunks!(dim)(1).map!(f);
}
```

**Comment by dataPulverizer** [comment]
Thanks, how do you use the master branch in Dub? `"~master"` doesn't seem to work anymore

**Comment by jmh530** [comment]
I have the same issue.

You could ditch dub for the command line or do something like
`dub add-local mir-algorithm-master 0.6.7`
and just trick dub into thinking it's the next version.

**Comment by 9il** [comment]
Do you need next release?

**Comment by 9il** [comment]
If so, please tag it) You should have permission

**Comment by dataPulverizer** [comment]
I was going to try the chunk module to see if it can act as R's apply-like function

I shall tag it thanks!

**Comment by dataPulverizer** [comment]
I have updated it. Seems to be taking ages to be updated in Dub

**Comment by wilzbach** [comment]
> Seems to be taking ages to be updated in Dub

FYI: The Dub registry crawls all packages every hour, one can manually login and trigger an instant crawl though.

**Comment by jmh530** [comment]
In addition to what @wilzbach says, nothing stops you from downloading it from [github](https://github.com/libmir/mir-algorithm/releases) and adding it to dub locally `dub add-local mir-algorithm-0.6.7 0.6.7`. Then when code.dlang.org is updated, you can remove local and dub update.

**Comment by dataPulverizer** [comment]
@jmh530 True

**Comment by jmh530** [comment]
I have tried
```
	import mir.ndslice : chunks, iota, map;
	import mir.math.sum : sum;
	
	auto s0 = iota(4, 10).chunks!(0)(1).sum;
	auto s1 = iota(4, 10).chunks!(1)(1).sum;
	auto m0 = iota(4, 10).chunks!(0)(1).map!(a => a + 1);
	auto m1 = iota(4, 10).chunks!(1)(1).map!(a => a + 1);
```
and none the different options worked with 0.6.7.

**Comment by 9il** [comment]
Could you please give a trivial loop based code example?  I do no understand the issue.

**Comment by dataPulverizer** [comment]
@jmh530 

* From my experimentation, the `map` function does not currently work with chunks, you need to use a `for`/`foreach` loop
*  Chunking wraps each block in a bracket

So alternatively:

```
import std.stdio : writeln;
import mir.ndslice : chunks, iota, map;
import mir.math.sum : sum;
import mir.ndslice.allocation : slice;

void main(){
    auto s0 = iota(4, 10).chunks!(0)(1);
    int agg;
    foreach(el; s0)
        agg += el.sum;
    writeln(agg);

    auto m0 = slice!ulong([4, 10], 0);
    for(int i = 0; i < s0.length; ++i){
        // chunking puts another set of brackets
        auto temp = s0[i][0];
        for(int j = 0; j < temp.length; ++j){
            m0[i, j] = temp[j] + 1;
        }
    }
    writeln(m0);
}
```

**Comment by 9il** [comment]
Chunks should not be used here. Combinations of pack, sum, and map should work.

**Comment by 9il** [comment]
It is weird to use chunks with the argument equals to 1

**Comment by 9il** [comment]
Ndslices has type built in dimensions selection . It is more powerful then R. Use pack or ipack to pack dimensions. Map applies to the outer most dimensions.

**Comment by 9il** [comment]
... in the dimension pack.

**Comment by 9il** [comment]
It should look like that : `a.universal.transposed.pack!1.each!(a=>a.each!"a-=b"(b));`. Does it work for you?

**Comment by 9il** [comment]
With zip,map,repeat you can make it lazy.

**Comment by dataPulverizer** [comment]
@9il 
What is the difference between `ipack` and `pack`?

**Comment by 9il** [comment]
One of them packs N most outers dims of the most outer pack. Another one packs N most inner dims of the most outer packs.

**Comment by dataPulverizer** [comment]
@9il I see thanks

BTW it would be nice for `chunks` be able to operate on arrays e.g. `arr.chunks!([0, 1])([4, 3])` shall I raise an issue?

**Comment by dataPulverizer** [comment]
@9il is there an equivalent of a `filter` function?

**Comment by 9il** [comment]
filter - no, we need allocators based appender first, PR is wellcome. appending - mir.ndslice.concatenation.

**Comment by 9il** [comment]
> BTW it would be nice for chunks be able to operate on arrays e.g. arr.chunks!([0, 1])([4, 3]) shall I raise another issue?

It would not work with the same complexity for arrays because D's nd-arrays are arrays of arrays.

**Comment by jmh530** [comment]
@9il Some very useful comments here. I'm still not entirely sure I have a handle on pack and ipack, but I feel like I'm heading in the right direction. 

I was at least able to write up an apply function that seems to work similar to R's version for two dimensions (not tested with tensors). I don't know how you feel about something like this for mir or numir, but my opinion is that it is a common enough idiom that it would be worth highlighting (and the fact that I've scratched my head for as long as I have to figure out how to do it!). 

```
template apply(alias f, size_t dim = 0)
{
	import mir.ndslice : isSlice;
	
	auto apply(Slice)(Slice slice)
		if (isSlice!Slice)
	{
		import mir.ndslice : pack, map;
		
		static if (dim == 0)
		{
			return slice.pack!1.map!(a => f(a));
		}
		else static if (dim == 1)
		{
			import mir.ndslice : universal, transposed;
			
			return slice.universal.transposed.pack!1.map!(a => f(a));
		}
		else
		{
			static assert(0, "dim must be 0 or 1");
		}
	}
}
```

**Comment by 9il** [comment]
> return slice.universal.transposed.pack!1.map!(a => f(a));

should be `transposed!dim`

**Comment by 9il** [comment]
and `map!f`

**Comment by 9il** [comment]
```
template apply(alias f, size_t dim = 0)
{
	import mir.ndslice : isSlice;
	
	auto apply(Slice)(Slice slice)
		if (isSlice!Slice)
	{
		import mir.ndslice : pack, map;
		static if (dim == 0)
		{
			return slice.pack!1.map!(a => f(a));
		}
		else
		{
			import mir.ndslice : universal, transposed;
			return slice.universal.transposed!dim.pack!1.map!f;
		}
	}
}
```

**Comment by 9il** [comment]
It should be `ipack!0`

**Comment by 9il** [comment]
`dim` is the dimension of that would be in result. All other dimensions are passed to `f`

**Comment by 9il** [comment]
`pack` and `ipack` has return types in the docs.

**Comment by jmh530** [comment]
I tried ipack!0, but it hadn't compiled in my sample example: `iota(4, 10).ipack!0.map!(sum)`

**Comment by 9il** [comment]
Ah, sorry, may bad! It should be `ipack!1` because it is dimension count

**Comment by jmh530** [comment]
It probably makes more sense to split this up to two functions. 

```
template byDim(size_t dim = 0)
{
	import mir.ndslice : isSlice;
	
	auto byDim(Slice)(Slice slice)
		if (isSlice!Slice)
	{
		import mir.ndslice : ipack;
		static if (dim == 0)
		{
			return slice.ipack!1;
		}
		else
		{
			import mir.ndslice : universal, transposed;
			return slice.universal.transposed!dim.ipack!1;
		}
	}
}

template apply(alias f, size_t dim = 0)
{
	import mir.ndslice : isSlice;
	
	auto apply(Slice)(Slice slice)
		if (isSlice!Slice)
	{
		import mir.ndslice : map;
		return slice.byDim!dim.map!f;
	}
}
```

**Comment by jmh530** [comment]
I was playing around with these to try to get the lazy sweep working. I got confused by the result from zip below.

```
	import std.stdio : writeln;
	import mir.ndslice : iota, map, repeat, zip, unpack;
	import mir.math.sum : sum;
	
	auto x = iota(4, 10);
	auto y = x.apply!(sum, 1).map!"a = a / 4";
	auto xx = x.byDim!1;
	auto yy = y.repeat(4).unpack.byDim!1;
	auto zz = zip!true(xx, yy);
	writeln(x);
	writeln(xx.front);
	writeln(y);
	writeln(yy.front);
	writeln(zz.front);
```
In particular, `zz.front` produces
```
[RefTuple!(uint, uint)(0, 15), RefTuple!(uint, uint)(10, 25), RefTuple!(uint, ui
nt)(20, 35), RefTuple!(uint, uint)(30, 45)]
```
I would have expected the second value there to be `15` each. I tried a few different iterations and it was like it was adding the first and second in all of them.

**Comment by 9il** [comment]
You may want to transposed yy

**Comment by jmh530** [comment]
@9il The byDim!1 function there had a transposed in it. I tried to make simpler examples below.

As far as I can tell it's related to `xx.strides` not equaling `yy.strides`, but letting `zip` believe they are. The problem is that  `auto yy = y.repeat(3).unpack.strides` equals `[0, 1]` and when you `ipack!1` or `pack!1`, the resulting strides are always `[0]`. 

```
	auto x = iota(2, 3);
	auto y = iota([3], 2);
	auto xx = x.ipack!1;
	auto yy = y.repeat(2).unpack.ipack!1;
	auto zz = zip!true(xx, yy);
	writeln(zz.front);
```
This produces  `[RefTuple!(uint, int)(0, 2), RefTuple!(uint, int)(1, 3), RefTuple!(uint, int)(2, 4)]`, which is what I would expect. I then try to do. However, if you `zz.popFront` and `writeln(zz.front)` you get `[RefTuple!(uint, int)(3, 5), RefTuple!(uint, int)(4, 6), RefTuple!(uint, int)(5, 7)]` instead of `[RefTuple!(uint, int)(3, 2), RefTuple!(uint, int)(4, 3), RefTuple!(uint, int)(5, 4)].`
```
	auto x = iota(2, 3);
	auto y = iota([3], 2);
	auto xx = x.universal.transposed!1.ipack!1;
	auto yy = y.repeat(2).unpack.universal.transposed!1.ipack!1;
	auto zz = zip!true(xx, yy);
	writeln(zz.front);
```
This produces `[RefTuple!(uint, int)(0, 2), RefTuple!(uint, int)(3, 5)]`, but I would have expected `[RefTuple!(uint, int)(0, 2), RefTuple!(uint, int)(3, 2)]`. It also doesn't make sense when you `zz.popFront` and `writeln(zz.front)` again. That gives `[RefTuple!(uint, int)(1, 3), RefTuple!(uint, int)(4, 6)]`, which doesn't make sense either. 

So I tried another version below 
```
	auto x = iota(2, 3);
	auto y = iota([2], 2);
	auto xx = x.universal.transposed!1.ipack!1;
	auto yy = y.repeat(3).unpack.ipack!1;
	auto zz = zip!true(xx, yy);
	writeln(zz.front);
```
and that gives `[RefTuple!(uint, int)(0, 2), RefTuple!(uint, int)(1, 3)]`, when I would have expected `[RefTuple!(uint, int)(0, 2), RefTuple!(uint, int)(3, 3)]`. Also, when you do the same procedure as above (popFronting and writeln front), you get `[RefTuple!(uint, int)(1, 3), RefTuple!(uint, int)(2, 4)]` when I would expect `[RefTuple!(uint, int)(1, 2), RefTuple!(uint, int)(4, 3)]`.

**Comment by 9il** [comment]
Yes, zip!true requires identical strides

**Comment by 9il** [comment]
You can use iterate in lock step using algorithm.each

**Comment by jmh530** [comment]
`each` is eager, correct? I was trying to make a lazy sweep. Recall your comment above: "With zip,map,repeat you can make it lazy."

I hadn't used `each` previously because your earlier example never worked that consistently for me. For instance
```
	auto x = iota(2, 3);
	auto y = iota([2], 2);
	x.universal.transposed.ipack!1.each!(a => a.each!"a-=b"(y));
```
Gives
```
..\..\dubFolder\mir-algorithm-0.6.7\source\mir\ndslice\algorithm.d-mixin-276(276
,4): Warning: calling mir.functional.naryFun!("a-=b").naryFun!(uint, int).naryFu
n without side effects discards return value of type uint, prepend a cast(void)
if intentional
dmd failed with exit code 1.
```

`x.universal.transposed.ipack!1.each!(a => a.each!"a-=b")(y);` also doesn't compile, but for different reasons.

**Comment by jmh530** [comment]
@9il There was a bug in `zip` that was driving me crazy. I have isolated it and suggested fix [here](https://github.com/libmir/mir-algorithm/issues/59)

**Comment by 9il** [comment]
If you want to create a lazy array with different strides then it should be an 1D slice composed of 1D slices.

**Comment by jmh530** [comment]
@9il What we were talking about above was a 1d slice composed of 1d slices, correct?

For instance,
auto x = iota(n).repeat(m).unpack.universal.transposed!1.ipack!1;
has properties `x.shape=[m]`, `x.strides=[1]`, and `x.packs=[1, 1]`. So it is a 1d slice composed of 1d slices. However, `x.unpack.strides=[1,0]`. This is only a problem when you consider something like 
`auto y = iota(m, n).universal.transposed!1.ipack!1;`
which has `y.unpack.strides=[1, m]` (but everything else matching up correctly). 

As a result, you can't apply zip to them. 

I was thinking that I could the steps in a reverse order, i.e. make it a matrix, then transpose it, then apply repeat, but it's a little painful and I couldn't get the strides matching properly. 

I don't doubt that it is possible to do this lazily. However, I'm not so sure I can figure it out with the current functionality. Perhaps adding an override for zip for slices with the same shape and strides but different unpacked strides might be the best way forward.

**Comment by jmh530** [comment]
"Perhaps adding an override for zip for slices with the same shape and strides but different unpacked strides might be the best way forward."

Actually, this might be harder than I thought...

**Comment by 9il** [comment]
> So it is a 1d slice composed of 1d slices.

No, it is packed slice. `map!"a"` can be used to make it real 1d slice composed of 1d slices.

**Comment by 9il** [comment]
Pure  1D slices (for example forced with `map!"a"` ) can be _always_ zipped together even if they have different strides. Just use `zip(a, b)` instead of `zip!true(a, b)` for pure  1D slices.

**Comment by 9il** [comment]
Yes, ndslices are crazy. But if you understand it once, then it you can do everything you can imagine )

**Comment by jmh530** [comment]
I imagine I could do everything, but the hope is that I can be productive as well. Hopeful I'll get there with a better understanding. This `map!"a"` trick is news to me (perhaps add a pack1d function that uses it?), but at least zip works sensibly now. 

Unfortunately I got stuck again on the crucial map function. I've included a simple example below showing where I'm at with this. I get an error that there is trouble deducing the lambda's type. 

```
void main()
{
	import mir.ndslice : iota, map, repeat, zip, unpack, universal, 
		transposed, ipack;
	
	size_t m = 3;
	size_t n = 5;
	auto xx = iota(m, n).universal.transposed!1.ipack!1.map!("a");
	auto yy = iota(n).repeat(m).unpack.universal.transposed!1.ipack!1.map!("a");
	auto zz = zip(xx, yy);
	auto result = zz.map!(a => a.map!"a+b");
}
```
I tried a few different options for `result` without much luck. The one I was really hoping would be right was
`auto result = zz.map!(a => zip(a.a, a.b).map!"a+b");`
since 
`auto result = zip(zz.front.a, zz.front.b).map!("a+b");`
works on an individual basis (i.e., I can popFront through the list and get the correct results).

**Comment by jmh530** [comment]
Sorry for the plethora of posts, but I got it working. The line should have been
`auto result = zz.map!((a, b) => zip(a, b).map!"a+b");`

So this gives something like the function below for sweep
```
template sweep(alias f, size_t dim = 0)
{
	import mir.ndslice : isSlice;
	
	auto sweep(Slice1, Slice2)(Slice1 s1, Slice2 s2)
		if (isSlice!Slice1 && isSlice!Slice1)
	{
		import mir.ndslice : map, zip, repeat, unpack, universal, transposed;
		
		return s1
				.byDim!dim
				.map!("a")
				.zip(s2
					.repeat(s1.universal.transposed!dim.length!dim)
					.unpack
					.byDim!dim
					.map!("a"))
				.map!((a, b) => zip(a, b).map!f);
	}
}
```

which can then be called
`auto a = sweep!((a, b) => a + b, 0)(iota(m, n), iota(n));`
or
`auto a = sweep!("a+b" 0)(iota(m, n), iota(n));`
and I imagine it would be possible to provide a specialization so that one only needs to write the operation "+" or "-".

**Comment by jmh530** [comment]
Also, the return type should probably be Slice1 instead of auto, but I wasn't sure how to coerce it back to the original type properly.

**Comment by 9il** [comment]
@dataPulverizer please take a look into the example, https://run.dlang.io/gist/e35ab6a6ea2c561a2454b7ed98c11c2e.

Feel free to reopen the issue if there is other case that can not be solved with Mir

**Comment by jmh530** [comment]
@9il I remember that example working before, but now it doesn't seem to work for me. Regardless, I recall it being complicated enough that it still probably can't hurt to have a function that handles this behavior.

**Comment by 9il** [comment]
Probably the example was look like
`matrix.byDim!dim.each!(v => fun(v, vec));`

It looks quite straightforward.

```d
/+dub.sdl: dependency "mir-algorithm" version="~>3.7.28" +/
import mir.ndslice;
import mir.algorithm.iteration;

alias V = Slice!(double*);
alias M = Slice!(double*, 2);

void foo(M matrix, V a, V b)
{
    matrix[] -= b;
    // or
    matrix.byDim!0.each!(v => v[] -= b);

    matrix.transposed[] += a;
    // or
    matrix.byDim!1.each!(v => v[] += a);
}

void main() {
    auto x = iota!int(2, 3).as!double.slice;
    auto a = [3.0, 4].sliced;
    auto b = [3.0, 4, 5].sliced;
    foo(x, a, b);
}
```
