### ISSUE TITLE
Mir and extern(C):

### ISSUE THREAD

**Issue by bubnenkoff** [libmir/mir-algorithm#84]
Does Mir compatible with `extern(C):`? If I am trying to build hello-world project like:

import core.stdc.stdio;
extern(C):
void main()
{
}

that have `mir` dependence in dub.sdl I am getting linking error.

**Comment by 9il** [comment]
Yes, it should be compatible with betterC mode.
Please provide full code sample including dub std. And detailed linking error that you have

**Comment by bubnenkoff** [comment]
![123](https://user-images.githubusercontent.com/6514326/30265852-1fc69b72-96e6-11e7-9da8-14d622eb22fd.png)

**Comment by 9il** [comment]
This does not looks like mir problem.

Hmm, does you program work if
1. you uncomment the code in the main (you need import std.algorithm)
and(!)
2. remove mir from dependency

BTW, I do not have windows, but https://github.com/libmir/mir have appveyor.
Does you dub package contains any other source files?

**Comment by bubnenkoff** [comment]
Hm, it's seems that problem not in mir, but in `extern(C)`

**Comment by 9il** [comment]
Another info: extern(C) does not mean betterC. mir-algorithm is compatible with betterC, Mir (sandbox v1.1.1) only partially compatible with betterC.

Your dub does not have betterC flag, but you have a linking errors like your Phobos is missing. Very strange.

**Comment by 9il** [comment]
> Hm, it's seems that problem not in mir, but in extern(C)

So I close it. Feel free to reopen if you find mir related issue

**Comment by bubnenkoff** [comment]
![111](https://user-images.githubusercontent.com/6514326/30266521-4d7cea92-96e8-11e7-8650-1da6b2e3ddeb.gif)

Странно, стоит удалить зависимость и начинает работать

**Comment by bubnenkoff** [comment]
@9il глянь все же на запись с экрана. странно что вываливается...

**Comment by 9il** [comment]
Потому, что там есть конструкторы. Разкомментируй код в main

**Comment by bubnenkoff** [comment]
А что там оставить то? `std.algorithm` не совместим же в betterC.

**Comment by 9il** [comment]
Есть betterC, есть extern(C). Это разные вещи

**Comment by 9il** [comment]
Mir (песочница) - тоже полностью не совместима. Только Mir Algorithm

**Comment by 9il** [comment]
Но тебе это не поможет, потому, что у тебя какие-то другие баги. betterC работает с betterC флагом.

**Comment by bubnenkoff** [comment]
На сколько я знаю `extern(C)` заставляет юзать соглашение о именовании С.
Вообще GC-free и betterC как я понимаю не синонимы. Верно?

Просто как я понимаю, чтобы писать либы Сишные мало использовать код без GC нужно чтобы он удовлетворял еще куче других условий.

**Comment by 9il** [comment]
в betterC все GC-free.

Да, куче еще. И собственно флаг betterC должен бытью

**Comment by bubnenkoff** [comment]
Может будет интересно https://github.com/dlang/dmd/commit/bac8aa59c75301c1c78c6296efddf5e4241e4a5e

**Comment by 9il** [comment]
спасибо)
