### ISSUE TITLE
Add band matrix iterator

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-algorithm#85]
The `windows` function in `mir.ndslice.topology` can be used to create a positive band matrix. However, there is no specific iterator for band matrices. The compressed band matrix format would allow for space savings, similar to the way that the StairsIterator works.

The key use-case I can think of is interacting with lapack functions that work on symmetric positive definite band matrices.

**Comment by 9il** [comment]
no plan to work on this feature for now
